const KEY="cosider_suivi_v2";let data=JSON.parse(localStorage.getItem(KEY)||"[]");const $=x=>document.getElementById(x);
function save(){localStorage.setItem(KEY,JSON.stringify(data));update()}
function go(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");if(id==="list")renderList();if(id==="report")report();scrollTo(0,0)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function card(x){let c=x.status==="Terminé"?"done":x.status==="En attente"?"wait":"";return `<div class="work"><div class="worktop"><b>${esc(x.type)}</b><span class="badge ${c}">${esc(x.status)}</span></div><div class="muted">📍 ${esc(x.zone)} · 👷 ${esc(x.team)}</div><div class="muted">Responsable : ${esc(x.resp||"-")} · ${x.date}</div><div class="bar"><i style="width:${x.percent}%"></i></div><div class="muted">${x.percent}% · ${x.qty?esc(x.qty)+" "+esc(x.unit||""):""}</div>${x.notes?`<div class="muted">${esc(x.notes)}</div>`:""}</div>`}
function update(){let n=data.length,r=data.filter(x=>x.status==="En cours").length,d=data.filter(x=>x.status==="Terminé").length,a=n?Math.round(data.reduce((s,x)=>s+x.percent,0)/n):0;$("nAll").textContent=n;$("nRun").textContent=r;$("nDone").textContent=d;$("nAvg").textContent=a+"%";$("recent").innerHTML=data.slice().reverse().slice(0,5).map(card).join("")||'<div class="card">Aucun travail enregistré.</div>';report()}
function renderList(){let q=($("search").value||"").toLowerCase(),f=$("filter").value;let a=data.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!f||x.status===f)).reverse();$("all").innerHTML=a.map(card).join("")||'<div class="card">Aucun résultat.</div>'}
function report(){let n=data.length,r=data.filter(x=>x.status==="En cours").length,d=data.filter(x=>x.status==="Terminé").length,a=n?Math.round(data.reduce((s,x)=>s+x.percent,0)/n):0;$("rAll").textContent=n;$("rRun").textContent=r;$("rDone").textContent=d;$("rAvg").textContent=a+"%"}
$("date").value=new Date().toISOString().slice(0,10);$("percent").oninput=e=>$("pct").textContent=e.target.value+"%";
$("form").onsubmit=e=>{e.preventDefault();let add=p=>{data.push({date:$("date").value,zone:$("zone").value,team:$("team").value,resp:$("resp").value,type:$("type").value,qty:$("qty").value,unit:$("unit").value,start:$("start").value,end:$("end").value,percent:+$("percent").value,status:$("status").value,notes:$("notes").value,photo:p});save();e.target.reset();$("date").value=new Date().toISOString().slice(0,10);$("pct").textContent="0%";go("list")};let f=$("photo").files[0];if(f){let r=new FileReader();r.onload=()=>add(r.result);r.readAsDataURL(f)}else add("")};
function exportCSV(){let h=["Date","Zone","Equipe","Responsable","Travaux","Quantite","Unite","Debut","Fin","Avancement","Statut","Remarques"],rows=data.map(x=>[x.date,x.zone,x.team,x.resp,x.type,x.qty,x.unit,x.start,x.end,x.percent+"%",x.status,x.notes]);let s=[h,...rows].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(";")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+s],{type:"text/csv;charset=utf-8"}));a.download="suivi_travaux.csv";a.click()}
function wipe(){if(confirm("Effacer toutes les données ?")){data=[];save()}}
$("dateNow").textContent=new Date().toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"});update();
let deferred;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("install").hidden=false});$("install").onclick=async()=>{if(deferred){deferred.prompt();deferred=null}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
